### ISSUE TITLE
This project is good, but how do you use it?

### ISSUE THREAD

**Issue by Juude** [zjutkz/Dexer#2]

**Comment by zjutkz** [comment]
@Juude 
首先看你是阿里的，就用中文回答了。
现在这个项目只能在app里使用，包括dump功能，只能dump到手机内或者logcat中。
其实这个项目建立的时候是想做一个比较完善的东西的，类似可以在命令行中操作，不过这段时间手头多了一个项目比较急，估计没什么时间维护它了，包括现在code item的解析也还是不支持的，有时间会继续维护。
另外可能它还有一个功能，可以当作[这篇文章](http://zjutkz.net/2016/10/27/dex文件结构及其应用/)的一个参考，深入理解一下dex文件格式。
最后谢谢提issue，祝工作顺心～

**Comment by Juude** [comment]
了解了，赞👍
